"""
True Classic Bot - Message Editor Module
Author: Aljay Leodones
Organization: True Classic
Details: Prepared for True Classic - The features of this Bot are original and can't be found in any other 3rd-party bots like Mee6, Dyno, etc

Adds a right-click (Apps) context menu on any message the bot posted and opens the
exact same editing surface as the Embed Editor - content, author, images, color,
fields, footer, multi-embed navigation - then writes the changes back onto the
live message instead of posting a new one.
"""

import discord
from discord.ext import commands
from discord import app_commands, ButtonStyle
from discord.ui import Button, View

import config
from utils import embed_builder
from modules.embed_editor import (
    EditorSession,
    EmbedState,
    EditEmbedView,
    MessageTextModal,
)

CONTEXT_MENU_NAME = "✏️ Edit Bot Message"
MAX_EMBEDS = 10


class SecuredView(View):
    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if not has_authorized_role(interaction.user):
            await interaction.response.send_message(
                embed=embed_builder.error_embed(
                    "Permission Denied",
                    "You do not have the required permissions to use the Message Editor."
                ),
                ephemeral=True
            )
            return False
        return True


def has_authorized_role(user) -> bool:
    roles = getattr(user, "roles", None)
    if not roles:
        return False
    user_roles = {role.id for role in roles}
    return any(role_id in user_roles for role_id in config.AUTHORIZED_ROLES)


# ---------------------------------------------------------------------------
# Session
# ---------------------------------------------------------------------------

class MessageEditSession(EditorSession):
    """An EditorSession bound to a message that already exists in the server."""

    def __init__(self, message: discord.Message):
        super().__init__()
        self.message = message
        self.status_line = None
        self.load_from_message(message)

    def load_from_message(self, message: discord.Message):
        self.message = message
        self.global_text = message.content or None

        # Only "rich" embeds are author-controlled. Link previews and media
        # unfurls are generated by Discord and cannot be edited or re-sent.
        self.embeds = [
            EmbedState.from_discord_embed(e)
            for e in message.embeds
            if e.type == "rich"
        ]
        self.skipped_auto_embeds = len(message.embeds) - len(self.embeds)

        if not self.embeds:
            self.embeds = [EmbedState()]
        self.current_index = 0

    def build_payload(self):
        """(content, embeds) exactly as they will be written to the message."""
        embeds = [e.to_discord_embed() for e in self.embeds if not e.is_empty()]
        return (self.global_text or None), embeds


# ---------------------------------------------------------------------------
# Message Editor Hub
# ---------------------------------------------------------------------------

class MessageEditHubView(SecuredView):
    def __init__(self, session: MessageEditSession):
        super().__init__(timeout=600)
        self.session = session
        self.create_dynamic_buttons()

    # -- Structure ----------------------------------------------------------

    def create_dynamic_buttons(self):
        # Rows 0 and 1 hold one selector per embed (5 per row, 10 embeds max).
        for idx in range(len(self.session.embeds)):
            label = f"E{idx+1} ✏️" if idx == self.session.current_index else f"E{idx+1}"
            style = ButtonStyle.blurple if idx == self.session.current_index else ButtonStyle.grey
            row = 0 if idx < 5 else 1

            btn = Button(label=label, style=style, row=row, custom_id=f"msg_edit_sel_{idx}")
            btn.callback = self.make_select_callback(idx)
            self.add_item(btn)

        jump_btn = Button(label="🔗 Jump to Message", style=ButtonStyle.link, url=self.session.message.jump_url, row=4)
        self.add_item(jump_btn)

    def make_select_callback(self, idx):
        async def callback(interaction: discord.Interaction):
            self.session.current_index = idx
            edit_view = EditEmbedView(self.session, self)
            await interaction.response.edit_message(
                embeds=[self.session.get_current_embed().to_discord_embed()],
                view=edit_view
            )
        return callback

    def rebuild(self):
        return MessageEditHubView(self.session)

    # -- Rendering ----------------------------------------------------------

    def get_hub_embed(self) -> discord.Embed:
        message = self.session.message
        content, embeds = self.session.build_payload()

        text_preview = "—"
        if content:
            text_preview = content if len(content) <= 200 else content[:197] + "..."

        embeds_summary = []
        for idx, e in enumerate(self.session.embeds):
            title = e.title or e.description or "(blank)"
            if len(title) > 60:
                title = title[:57] + "..."
            flag = " *(empty — will be dropped)*" if e.is_empty() else ""
            embeds_summary.append(f"Embed #{idx+1:02d}: {title}{flag}")

        hub = embed_builder.base_embed(
            title="✏️ Message Editor",
            description=(
                f"Editing a live message in {message.channel.mention} "
                f"(`{message.id}`).\n"
                "Use the **E#** buttons for the same controls as the Embed Editor. "
                "Nothing changes on the real message until you press **💾 Save Changes**."
            ),
            color=embed_builder.COLOR_INFO,
            footer_text=f"{embed_builder.BOT_NAME} • Message Editor"
        )
        hub.add_field(name="Message Text", value=text_preview, inline=False)
        hub.add_field(name="Editable Embeds", value=str(len(embeds)), inline=True)
        hub.add_field(name="Attachments", value=str(len(message.attachments)) + " (kept as-is)", inline=True)
        hub.add_field(name="Embeds List", value="\n".join(embeds_summary) or "—", inline=False)

        if self.session.skipped_auto_embeds:
            hub.add_field(
                name="Note",
                value=(
                    f"{self.session.skipped_auto_embeds} auto-generated preview embed(s) "
                    "(link/media unfurls) are not editable and were left out."
                ),
                inline=False
            )
        if self.session.status_line:
            hub.add_field(name="Status", value=self.session.status_line, inline=False)

        return hub

    def get_hub_embeds(self) -> list:
        # Hub summary plus a live preview of what will be written back.
        # A message carries at most 10 embeds, so cap the previews at 9.
        _, previews = self.session.build_payload()
        return [self.get_hub_embed()] + previews[:9]

    async def refresh_hub(self, interaction: discord.Interaction, defer=True):
        new_view = self.rebuild()
        if interaction.is_expired():
            return
        if interaction.response.is_done():
            # Reached after a defer() on a button press; edits the ephemeral hub in place.
            await interaction.edit_original_response(
                embeds=new_view.get_hub_embeds(),
                view=new_view
            )
        else:
            await interaction.response.edit_message(
                embeds=new_view.get_hub_embeds(),
                view=new_view
            )

    # -- Buttons ------------------------------------------------------------

    @discord.ui.button(label="📝 Message Text", style=ButtonStyle.grey, row=2)
    async def edit_message_text(self, interaction: discord.Interaction, button: Button):
        modal = MessageTextModal(self.session, self.refresh_hub)
        await interaction.response.send_modal(modal)

    @discord.ui.button(label="➕ Add Embed", style=ButtonStyle.green, row=2)
    async def add_embed(self, interaction: discord.Interaction, button: Button):
        if len(self.session.embeds) >= MAX_EMBEDS:
            await interaction.response.send_message(
                embed=embed_builder.error_embed("Limit Reached", f"A message can hold a maximum of {MAX_EMBEDS} embeds."),
                ephemeral=True
            )
            return

        self.session.embeds.append(EmbedState())
        self.session.current_index = len(self.session.embeds) - 1
        self.session.status_line = None
        print(f"[Message Editor] Added blank Embed #{len(self.session.embeds)} to message {self.session.message.id}")
        await self.refresh_hub(interaction)

    @discord.ui.button(label="🔄 Reload from Message", style=ButtonStyle.grey, row=2)
    async def reload_from_message(self, interaction: discord.Interaction, button: Button):
        await interaction.response.defer()
        try:
            fresh = await self.session.message.channel.fetch_message(self.session.message.id)
        except discord.NotFound:
            self.session.status_line = "🔴 That message no longer exists — it was deleted."
            await self.refresh_hub(interaction)
            return
        except discord.HTTPException as e:
            self.session.status_line = f"🔴 Could not re-fetch the message: `{e}`"
            await self.refresh_hub(interaction)
            return

        self.session.load_from_message(fresh)
        self.session.status_line = "🔄 Reloaded from the live message — unsaved edits were discarded."
        print(f"[Message Editor] Reloaded state from message {fresh.id}")
        await self.refresh_hub(interaction)

    @discord.ui.button(label="💬 Syntax Guide", style=ButtonStyle.grey, row=3)
    async def syntax_guide(self, interaction: discord.Interaction, button: Button):
        guide = (
            "**Discord Markdown Guide:**\n"
            "• *Italics*: `*text*` or `_text_`\n"
            "• **Bold**: `**text**`\n"
            "• ***Bold Italics***: `***text***`\n"
            "• __Underline__: `__text__`\n"
            "• ~~Strikethrough~~: `~~text~~`\n"
            "• Code Block: \\`\\`\\`text\\`\\`\\`\n"
            "• Inline Code: \\`text\\`\n"
            "• Mentions: `<@user_id>`, `<@&role_id>`, `<#channel_id>`\n"
            "• Custom Links: `[label](url)` (Only works inside Embed Descriptions or Fields)"
        )
        await interaction.response.send_message(guide, ephemeral=True)

    @discord.ui.button(label="💾 Save Changes", style=ButtonStyle.danger, row=3)
    async def save_changes(self, interaction: discord.Interaction, button: Button):
        content, embeds = self.session.build_payload()

        if content is None and not embeds:
            await interaction.response.send_message(
                embed=embed_builder.error_embed(
                    "Nothing to Save",
                    "A message cannot be blank. Add message text or fill in at least one embed."
                ),
                ephemeral=True
            )
            return

        await interaction.response.defer()
        try:
            updated = await self.session.message.edit(content=content, embeds=embeds)
            self.session.message = updated
            self.session.status_line = f"🟢 Saved. The message in {updated.channel.mention} is now live with these changes."
            print(f"[Message Editor] {interaction.user} saved edits to message {updated.id} in #{getattr(updated.channel, 'name', updated.channel.id)}")
        except discord.NotFound:
            self.session.status_line = "🔴 That message no longer exists — it was deleted."
            print(f"[Message Editor] Save failed: message {self.session.message.id} not found")
        except discord.Forbidden:
            self.session.status_line = "🔴 Missing permissions to edit that message."
            print(f"[Message Editor] Save failed: forbidden on message {self.session.message.id}")
        except discord.HTTPException as e:
            self.session.status_line = f"🔴 Discord rejected the edit: `{e}`"
            print(f"[Message Editor] Save failed on message {self.session.message.id}: {e}")

        await self.refresh_hub(interaction)

    @discord.ui.button(label="❌ Close Editor", style=ButtonStyle.secondary, row=3)
    async def close_editor(self, interaction: discord.Interaction, button: Button):
        await interaction.response.edit_message(
            embeds=[embed_builder.info_embed("Message Editor Closed", "No further changes will be applied.")],
            view=None
        )


# ---------------------------------------------------------------------------
# Context menu entry point
# ---------------------------------------------------------------------------

@app_commands.guild_only()
async def edit_bot_message(interaction: discord.Interaction, message: discord.Message):
    if not interaction.guild:
        await interaction.response.send_message("This can only be used inside a server.", ephemeral=True)
        return

    if not has_authorized_role(interaction.user):
        await interaction.response.send_message(
            embed=embed_builder.error_embed("Permission Denied", "You do not have permission to edit the bot's messages."),
            ephemeral=True
        )
        return

    if message.author.id != interaction.client.user.id:
        await interaction.response.send_message(
            embed=embed_builder.error_embed(
                "Not My Message",
                f"Discord only lets a bot edit messages it posted itself, and this one is from "
                f"{message.author.mention}.\n\nTo compose something new, use **Embed Editor** on the Mod Panel."
            ),
            ephemeral=True
        )
        return

    session = MessageEditSession(message)
    hub_view = MessageEditHubView(session)

    print(f"[Message Editor] {interaction.user} opened the editor for message {message.id} in #{getattr(message.channel, 'name', message.channel.id)}")
    await interaction.response.send_message(
        embeds=hub_view.get_hub_embeds(),
        view=hub_view,
        ephemeral=True
    )


class MessageEditorCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot


async def setup(bot):
    await bot.add_cog(MessageEditorCog(bot))

    # A stale entry can linger if a previous load half-failed, so clear before adding.
    bot.tree.remove_command(CONTEXT_MENU_NAME, type=discord.AppCommandType.message)
    bot.tree.add_command(app_commands.ContextMenu(name=CONTEXT_MENU_NAME, callback=edit_bot_message))
    # Logged without the emoji: a cp1252 Windows console raises UnicodeEncodeError on it,
    # which would abort the whole extension load.
    print("[System] Registered message context menu: Edit Bot Message")


async def teardown(bot):
    # Hot-reload calls teardown then setup; without this the re-add raises
    # CommandAlreadyRegistered and the module fails to reload.
    bot.tree.remove_command(CONTEXT_MENU_NAME, type=discord.AppCommandType.message)
